### ISSUE TITLE
TypeError: Expected cv::UMat for argument 'array'

### ISSUE THREAD

**Issue by shanavajk** [SSARCandy/panoramas-image-stitching#10]
Traceback (most recent call last):
  File "D:\python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\python\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\shahnavaj.k\Downloads\panoramas-image-stitching-master\src\utils.py", line 75, in cylindrical_projection
    x, y, w, h = cv2.boundingRect(contours[0])
TypeError: Expected cv::UMat for argument 'array'
"""

**Comment by SSARCandy** [comment]
what is your Python, OpenCV version?

**Comment by shanavajk** [comment]
python 3.7.3
cv2 4.1.0

**Comment by SSARCandy** [comment]
Can you try opencv3?

**Comment by shanavajk** [comment]
Ok thanks
