### ISSUE TITLE
[Help] Problem to run project

### ISSUE THREAD

**Issue by teckefaro** [SSARCandy/panoramas-image-stitching#9]
I was trying to run the project and I got this error:
Python 3.7
matplotlib==3.1.1
numpy==1.17.1
opencv-python==4.1.1.26

`venv) D:\GEOPIX\PROJETOS_PYTHON\stitch>python ./main.py ./input_image/grail
Warp images to cylinder
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python37\Lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\GEOPIX\PROJETOS_PYTHON\stitch\utils.py", line 76, in cylindrical_projection
    x, y, w, h = cv2.boundingRect(contours[0])
TypeError: Expected Ptr<cv::UMat> for argument '%s'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./main.py", line 29, in <module>
    cylinder_img_list = pool.starmap(utils.cylindrical_projection, [(img_list[i], focal_length[i]) for i in range(len(img_list))])
  File "C:\Python37\Lib\multiprocessing\pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Python37\Lib\multiprocessing\pool.py", line 657, in get
    raise self._value
TypeError: Expected Ptr<cv::UMat> for argument '%s'
`

**Comment by oiacrasec** [comment]
The problem is your libs version.

matplotlib==3.1.1
numpy==1.17.1
opencv-contrib-python==3.4.2.17
opencv-python==3.4.2.17

**Comment by SSARCandy** [comment]
Thanks 😊
